Formatting

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -41,7 +41,7 @@ jobs:
         run: npm install -g pnpm && pnpm install
 
       - name: Run npm audit
-        run: pnpm audit || true  # Don't fail the build, but report issues
+        run: pnpm audit || true # Don't fail the build, but report issues
 
       # Initialize CodeQL
       - name: Initialize CodeQL
